---
  title: Diego Cuevas
  description: Software Engineer
  language: en
  repository: https://github.com/DiegoCuevas/personal-site/
  email: diegocuevas579@gmail.com
  social:
    twitter: diegogcuevas
    github: DiegoCuevas
    linkedin: diegogcuevas
  navigation:
  incremental: false