---
  title: Diego Cuevas
  description: Software Engineer
  domain: https://diegocuevas.dev
  language: es
  repository: https://github.com/DiegoCuevas/personal-site/
  email: diegocuevas579@gmail.com
  social:
    github: DiegoCuevas
    linkedin: diegogcuevas
  analytics: UA-164782098-1
  navigation:
  incremental: false